### ISSUE TITLE
CLI: Add RPC control plane

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/kotlin-ice-adapter#4]
In CLI mode the ICE adapter is exchanging commands via RPC.
A first implementation should be compatible to the java-ice-adapter RPC protocol ([link](https://github.com/FAForever/java-ice-adapter/tree/master/ice-adapter/src/main/java/com/faforever/iceadapter/rpc)).

**Comment by BlackYps** [comment]
can you elaborate what needs to be done?

**Comment by Brutus5000** [comment]
Open a RPC server just like in the java-ice-adapter (see the link) from the com.nbarraille.jjsonrpc library.
Basically all methods in the ControlPlane interface have a corresponding message on the RPC service. So incoming rpc message -> call the IceAdapter method.
There are also outgoing messages. I think so far it's only the `onIceCandidatesGathered` callback in the IceAdapter constructor. There you basically give it a lambda to send this message via RPC to the FAF client.
